# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
image: python:3.8
stages:
- build
- deploy
- test
before_script:
- pip install -r requirements.txt
gitversion:
  stage: build
  script:
  - scripts/gitversion-dependencies.sh
  - "./gitversion path $(pwd) > gitversion-ext.json"
  - cat gitversion-ext.json
  - FullSemVer=$(./yq r gitversion-ext.json FullSemVer)
  - sed "s/^\(\s*version\s*:\s*\).*/\1 $FullSemVer/" scrapinghub.yml > scrapinghub-new.yml
  - mv scrapinghub-new.yml scrapinghub.yml
  artifacts:
    paths:
    - scrapinghub.yml
  only:
  - master
scrapinghub:
  stage: deploy
  script:
  - scripts/shub-dependencies.sh
  - scripts/deploy.sh
  only:
  - master
  environment:
    name: scrapinghub
    url: https://app.scrapinghub.com/p/467634
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
