image: python:3.9-slim

stages:
  - build
  - test
  - deploy

include:
  - template: Security/SAST.gitlab-ci.yml

gitversion:
  stage: build
  script:
    - scripts/gitversion-dependencies.sh
    - "./gitversion path $(pwd) > gitversion-ext.json"
    - cat gitversion-ext.json
    - FullSemVer=$(./yq r gitversion-ext.json FullSemVer)
    - sed "s/^\(\s*version\s*:\s*\).*/\1 $FullSemVer/" scrapinghub.yml > scrapinghub-new.yml
    - mv scrapinghub-new.yml scrapinghub.yml
  artifacts:
    paths:
      - scrapinghub.yml
  only:
    - master

scrapinghub:
  stage: deploy
  script:
    - pip install -r requirements.txt
    - scripts/shub-dependencies.sh
    - scripts/deploy.sh
  only:
    - master
  environment:
    name: scrapinghub
    url: https://app.scrapinghub.com/p/467634
